name: Build and test L2s

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout git submodules
      run: git submodule update --init --recursive
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install -y libelf-dev binutils-powerpc64le-linux-gnu gcc-powerpc64le-linux-gnu
    - name: defconfig
      run: ./make kvm_l1_defconfig
    - name: Build
      run: ./make -j $(nproc)
    - name: Test
      run: ./test_L1.sh

    - name: Kernel artifact
      uses: actions/upload-artifact@v3
      with:
        name: vmlinux
        path: output/images/vmlinux
    - name: Rootfs artifact
      uses: actions/upload-artifact@v3
      with:
        name: rootfs.cpio
        path: output/images/rootfs.cpio
